import Head from 'next/head';
// import Image from 'next/image';

const SixthSection = () => {
    return (
        <div className="container mx-auto px-4 py-16">

            <Head>
                <title>Next.js App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <h1 className="text-4xl font-bold   
 text-center mb-8">
                A Powerful Framework for Building High-Performance, Server-Rendered Web Applications
            </h1>

            <div className="flex justify-center space-x-4 mb-8">
                <div className="flex items-center space-x-2">
                    <svg className="w-6 h-6 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path
                            strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7"></path>
                    </svg>

                    <p className="text-gray-500">Superior Developer Experience</p>
                </div>
                <div className="flex items-center space-x-2">
                    <svg className="w-6 h-6 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path
                            strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7"></path>
                    </svg>

                    <p className="text-gray-500">Battle-Tested in Production</p>
                </div>
                <div className="flex items-center space-x-2">
                    <svg className="w-6 h-6 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path
                            strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7"></path>
                    </svg>

                    <p className="text-gray-500">Performance-Obsessed Stack</p>
                </div>
            </div>

            <p className="text-center text-gray-500 mb-8">
                Deploy your Next.js site globally in seconds, with zero configuration. Just Git push to get started.
            </p>

            <div className="flex justify-center space-x-4">
                <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">

                    Learn About Managed Next.js
                </button>
                <button className="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded">
                    Contact Sales
                </button>
            </div>
        </div>
    )
}

export default SixthSection